# Generated by Django 2.0.2 on 2018-05-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_job', models.ImageField(upload_to='images/')),
                ('sumary', models.CharField(max_length=400)),
                ('technology', models.CharField(max_length=400)),
            ],
        ),
    ]
